# # #

name: 'Docs | Build & Push'

# # #

on:
  workflow_dispatch:

# # #

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  frontend:
    name: frontend (NextJS)
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          file: ./dockerfile
          tags: ghcr.io/tmlmobilidade/go-docs:production
          build-args: |
            ENVIRONMENT=production