name: Publish Fumadocs to GitHub Pages

on:
  push:
    branches: ["production"]
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

env:
  ENVIRONMENT: "production"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout content repository
        uses: actions/checkout@v4
        with:
          repository: carrismetropolitana/ISO
          path: content

      - name: Checkout docs repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Copy content into docs
        run: |
          # Clean old content inside docs
          rm -rf ./docs/content

          # Create new folders
          mkdir -p ./docs/content/docs
          mkdir -p ./docs/content/blog

          # Copy docs if they exist
          if [ -d content/docs ]; then
              cp -R content/docs/* docs/content/docs/
          fi

          # Copy blog if they exist
          if [ -d content/blog ]; then
              cp -R content/blog/* docs/content/blog/
          fi

          # Normalize filenames (docs + blog)
          for folder in docs/content/docs docs/content/blog; do
            find "$folder" -depth | while read path; do
              base="$(basename "$path")"
              dir="$(dirname "$path")"
              normalized="$(echo "$base" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')"
              if [ "$base" != "$normalized" ]; then
                mv "$path" "$dir/$normalized"
              fi
            done
          done
        shell: bash

      - name: Clean docs
        run: npx -y @tmlmobilidade/repo-rinse
        working-directory: docs

      - name: Install dependencies
        run: npm install
        working-directory: docs

      - name: Build site
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          NEXT_PUBLIC_ENVIRONMENT: ${{ env.ENVIRONMENT }}
          GITHUB_PAGES: "true"
        run: npm run build
        working-directory: docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
