name: Publish Fumadocs to GitHub Pages

on:
  push:
    branches: ["production"]
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GITHUB_PAGES: "true"
  ENVIRONMENT: "production"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout content repository
        uses: actions/checkout@v4
        with:
          repository: carrismetropolitana/ISO
          ref: production
          path: content

      - name: List content repo
        run: |
          echo "Conteúdo do repo content:"
          ls -R content

      - name: Checkout docs repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Copy "Carris Metropolitana" into docs/content
        run: |
          # Remove conteúdo antigo
          rm -rf ./docs/content
      
          # Criar pasta de destino
          mkdir -p ./docs/content
      
          # Copiar a pasta inteira temporariamente
          cp -R "content/Carris Metropolitana" ./temp-cm
      
          # Mover apenas o conteúdo para docs/content
          mv ./temp-cm/* ./docs/content/
      
          # Remover a pasta temporária
          rm -rf ./temp-cm
      
          # Normalizar nomes de ficheiros e pastas
          find docs/content -depth | while read path; do
            base="$(basename "$path")"
            dir="$(dirname "$path")"
            normalized="$(echo "$base" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')"
            if [ "$base" != "$normalized" ]; then
              mv "$path" "$dir/$normalized"
            fi
          done
        shell: bash
        
      

      - name: Clean docs
        run: npx -y @tmlmobilidade/repo-rinse
        working-directory: docs

      - name: Install dependencies
        run: npm install
        working-directory: docs

      - name: Build site
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          NEXT_PUBLIC_ENVIRONMENT: ${{ env.ENVIRONMENT }}
          GITHUB_PAGES: "true"
        run: npm run build
        working-directory: .

      - name: Copy .next static files
        run: |
          mkdir -p ./out/_next
          cp -R ./.next/static ./out/_next/static
        shell: bash

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
